### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by adriancole** [comment]
hi eddu. this will add more stuff to the jar.. what is it buying us?

**Comment by eddumelendez** [comment]
@adriancole those jars are mark as `optional`.

`spring-boot-configuration-processor` dependency will provide metadata to be provided in the IDE when developers are looking for a specific property.

`spring-boot-autoconfigure-processor` dependency helps startup time for spring-boot applications since metadata for autoconfigurations are crated by this dependency

**Comment by adriancole** [comment]
yeah this is the opposite of what we want to do.

we definitely do not want starters. this is not normal spring boot and we have had numerous problems with people and custom packaged servers.

It consumes our chat and sometimes even email support, sometimes many people cross posting. We never want to encourage making custom servers and I think creating metadata such as in #4 walks directly towards that by making it easier to do exactly what we always ask people not to do.

Let's please not do anything that encourages this practice of making servers in IDE

https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/main/java/zipkin/server/EnableZipkinServer.java#L25-L32

**Comment by eddumelendez** [comment]
I was not aware of that. Thanks for letting me know. I think the same applies for the other PRs

**Comment by adriancole** [comment]
yeah It is very ironic timing :) thanks for your understanding. We have this problem in general because everyone sees this is spring boot and naturally thinks it should be bootified.

**Comment by adriancole** [comment]
fyi here's some links maybe help. Ex thing from this morning https://github.com/openzipkin/zipkin-gcp/issues/130#issuecomment-531620576

Also the more people mistake us for an IDE server, the less our advice is listened to. Ex this person raised several issues after trying to custom integrate a server. it has really strained our support https://github.com/openzipkin/zipkin/issues/2798

**Pull request closed without merging**
